# Generated by Django 4.0 on 2024-02-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
